### ISSUE TITLE
Onboarding: Navigation logic

### ISSUE THREAD

**Issue by rodvar** [bisq-network/bisq-mobile#109]
We now have enough components setup to implement this properly.

Navigation should work as follows.

**A) Fully setup case**

 1. Show Splash Screen with connectivity progress
 2. if any connectivity issue show dialog explaining the problem with a button to open settings, otherwise land on Home

**B) First time use / No profile setup**

 1. Show Splash Screen and go to create profile
 2. after profile is created if any connectivity issue show dialog explaining the problem with a button to open settings, otherwise land on Home
 
 **C) `xClients` - No connectivity details**
 
 1. Show Splash Screen
 2. no trusted no configured found -> go to Trusted node setup screen
 3. proceed as (A) or (B) accordingly.

**Comment by nostrbuddha** [comment]
I like to do this, once I fix the OfferCard layout.

**Comment by rodvar** [comment]
From discussions we had whilst developing settings, we discover the following things that would be good to address in the context of this card:

 1. **Onboarding Setup Screens**: when onboarding redirects the user to a settings screen (e.g. setup trusted node) you shouldn't be able to go back normally as it doesn't make sense to get back to the onboarding setup. We need a consistent way to block the user from normal back navigation and maybe show a dialog to ask if they want to quit?). Ideally this should be bound to BasePresenter so that we can control which presenters block back navigation easily
 2. deep link navigation: not sure if we want to do it from onboarding, but we will need for other use cases (like notifications) a way to deep link the user to nested screen (like in settings). This one is optional and can be strip out into a different issue.

**Comment by nostrbuddha** [comment]
I will do this, this week

**Comment by rodvar** [comment]
@nostrbuddha this has been merged with last Henrik's PR. Just a nit, when nothing is setup (fresh install), the user gets offered a "Create Profile" button, but when clicking it it goes into Trusted Node first.

Text should change based on config, or at least use a generic "Get Started" and then the trusted node app should have a title/description on top explaining why the trusted node setup is needed like "Setup your trusted node ip:port to connect to Bisq network"
