### ISSUE TITLE
Create Offer / Take Offer: currency list should not show offers data

### ISSUE THREAD

**Issue by rodvar** [bisq-network/bisq-mobile#110]
<img width="336" alt="Screenshot 2024-12-12 at 10 57 17" src="https://github.com/user-attachments/assets/432e2533-aa26-46b4-8596-4eb190319662" />

Hide the offers text on the currency items when creating/taking a trade

**Comment by nostrbuddha** [comment]
Actually the offers was shown in the Bisq 2 desktop app. So I replicated the same.

**Comment by rodvar** [comment]
> Actually the offers was shown in the Bisq 2 desktop app. So I replicated the same.

I guess the logic is to know how used is the currency..? I'll close this as invalid for now and we'll discuss later on if we want it in or not
