### ISSUE TITLE
Take Offer: cards not constrained

### ISSUE THREAD

**Issue by rodvar** [bisq-network/bisq-mobile#111]
<img width="414" alt="Screenshot 2024-12-12 at 10 53 18" src="https://github.com/user-attachments/assets/cc6fc4ae-e39f-4b01-b628-f6e28bcde3db" />

**pre**: setup your local env with 2+ offers on any currency
**steps**

 1. open the app (any of the 3)
 2. go to buy/sell
 3. tap on the currency with offers pre-setup
 4. Observe

**Expected**:  cards with offers should take as much width of the screen as possible with padding as per designs, height should be limited to allow several cards to fit in devices screen. User can scroll up/down to see more offers if there are many. Also Buy from / Sell to labels are wrong, when tapping on the selector both text changes.
**Obtained**: wrong padding, wrong fits, wrong top labels see expected for details.

**Comment by nostrbuddha** [comment]
This is for me. Please assign.

**Comment by rodvar** [comment]
fixed with the above PR
