### ISSUE TITLE
Currencies List: Search bar filter

### ISSUE THREAD

**Issue by rodvar** [bisq-network/bisq-mobile#112]
<img width="414" alt="Screenshot 2024-12-12 at 10 53 18" src="https://github.com/user-attachments/assets/48894c4b-631d-47fb-a66e-f9a498794725" />

This card is to implement the search bar filter. Currently is not allowing any text input. With every char input it should filter the matching currencies to faciliate to the user to click the one he is looking for.

**Comment by nostrbuddha** [comment]
This is for me. Please assign to me.

**Comment by rodvar** [comment]
this has been fixed with #128
