### ISSUE TITLE
Initial App Design

### ISSUE THREAD

**Issue by rodvar** [bisq-network/bisq-mobile#2]
- focus on Android first
 - respectful of Bisq 2 Look&Feel
 - UX -> focus on trading in Bisq, simple minimalistic app fast and clear to go around

**Comment by nostrbuddha** [comment]
Hi. You can assign this to me.

**Comment by nostrbuddha** [comment]
Created PR for this @ https://github.com/bisq-network/bisq-mobile/pull/25

**Comment by rodvar** [comment]
Initial designs ready, see merged PR.
