### ISSUE TITLE
App Skeleton Main Screen: Buy/Sell currencies listing screen

### ISSUE THREAD

**Issue by rodvar** [bisq-network/bisq-mobile#20]
![Screenshot from 2024-10-30 17-45-39](https://github.com/user-attachments/assets/a685dc54-cbd9-45b8-9e8b-a32173d17cb3)

This task includes the implementation of the view using mocked data / mocked presenter calls whenever needed.

**note**: @nostrbuddha has been working on this one in the past few days

**Comment by nostrbuddha** [comment]
You can assign this to me.

**Comment by nostrbuddha** [comment]
This should also cover

Filter popup (4aa)

Refer: https://www.figma.com/design/IPnuicxGKIZXq28gybxOgp/Xchange?node-id=629-14425&t=0NTIOxzkLLAe5cmu-1

**Comment by rodvar** [comment]
@nostrbuddha can we close this one?

**Comment by nostrbuddha** [comment]
Yet to do Filter popup. Will do this by this weekend.

**Comment by rodvar** [comment]
ready
