### ISSUE TITLE
App Skeleton

### ISSUE THREAD

**Issue by rodvar** [bisq-network/bisq-mobile#21]
![Screenshot from 2024-10-30 21-12-24](https://github.com/user-attachments/assets/32a37d94-b86b-4d80-9656-170acaed8fd6)

This issue involves the skeleton of the main interaction screen for the apps UI. As shown on the screenshot above (taken from designs), this is (from top to bottom)

1. App Header: Title (changes with bottom menu selector) + Notification avatar + profile avatar
2. Menu screen content
3. Menu control with 4 buttons: Home, Buy/Sell, My Trades, Settings

In the context of this issue, all the skeleton UI should be implemented (avatars and menu content screens should be mocked) along with the functionality of changing screen based on the selected menu option. Default option is Home.

**Comment by nostrbuddha** [comment]
Great. You can assign this to me.

**Comment by rodvar** [comment]
this has been done with #36
