### ISSUE TITLE
App Skeleton Main Screen: Home

### ISSUE THREAD

**Issue by rodvar** [bisq-network/bisq-mobile#23]
<img width="222" alt="Screenshot 2024-10-31 at 09 59 06" src="https://github.com/user-attachments/assets/ff32ee6a-09a0-40d4-b900-55d708bd8145">

 - Mock all data using the observer/observable pattern with Kotlinb StateFlow (See example of App.kt view code)
 - text can be hardcoded for now ( a plus for setting up the basis for easy i18n of text, though English is the only language included for the MVP)
 - Links can be hardcoded to just show and alert "link clicked" for now
 - Make sure the content is scrollable vertically

**Comment by nostrbuddha** [comment]
I will take this up.

**Comment by rodvar** [comment]
done with recent merges, feature/based cards to make the UI usable will be created from now on
