### ISSUE TITLE
App Skeleton Main Screen: My Trades

### ISSUE THREAD

**Issue by rodvar** [bisq-network/bisq-mobile#24]
<img width="233" alt="Screenshot 2024-10-31 at 10 07 07" src="https://github.com/user-attachments/assets/eebbf7fb-b259-481d-8311-2a4bf8dd7ec9">

 - Mock all data using the presenter KT StateFlow observer pattern (suggested to mock some offers)
 - if Offer domain model is not in the domain module yet, create a basic one
 - When there are no offers available (presenter state flow), show a blank screen for now (placeholder UI will be developed in another issue)

**Comment by nostrbuddha** [comment]
I will take this up.

**Comment by rodvar** [comment]
done with recent merges, feature/based cards to make the UI usable will be created from now on
