### ISSUE TITLE
Add Bisq 2 library dependencies

### ISSUE THREAD

**Issue by HenrikJannsen** [bisq-network/bisq-mobile#5]
After https://github.com/bisq-network/bisq2/issues/2951 is implemented we can resolve the Bisq 2 dependencies.

We should avoid duplicating complex gradle tasks already present in Bisq 2. 
@alvasw is re-using Bisq 2 gradle tasks in Bisq 1, he might have suggestions how to do that best.

 - at the moment the bisq2 jars get published in the local maven repository only, so running the `publishAll` bisq2 gradle task is a must before tackling this one (related PR: https://github.com/bisq-network/bisq2/pull/2965)
 - this is a breaking change for the CI setup as currently we don't have a publication to mavenCentral or other maven repos. Ideally this just be dealt in the context of this issue, otherwise it should comment the `androidNode` related code of the github workflow `ci.yml` file to avoid breaking builds.

**Comment by rodvar** [comment]
work on this can start now though not merged yet, leveraging this PR -> https://github.com/bisq-network/bisq2/pull/2965

**Comment by rodvar** [comment]
the above PR is pretty much done, just need to either

 - remove androidNode from CI builds (cause it will fail being the bisq-core only maven-local publisheable) or
 - publish the bisq2 core libs to a maven repo like the ones used for some of our contributors libs

**Comment by rodvar** [comment]
we decided to remove `androidNode` from CI for now, I'll create an issue to fix this later down the road

**Comment by rodvar** [comment]
https://github.com/bisq-network/bisq-mobile/pull/29 merged
