### ISSUE TITLE
Account

### ISSUE THREAD

**Issue by nostrbuddha** [bisq-network/bisq-mobile#51]
10 a) & b)

<img width="529" alt="Screenshot 2024-12-12 at 15 31 33" src="https://github.com/user-attachments/assets/75a7705d-05ef-4ca0-96c6-14c54ec0a237" />

10 c) & d)

<img width="639" alt="Screenshot 2024-12-12 at 15 37 55" src="https://github.com/user-attachments/assets/fdf7c076-8d30-403c-80fa-82f0a8dc1529" />

Refer: https://www.figma.com/design/IPnuicxGKIZXq28gybxOgp/Xchange?node-id=629-14425&t=0NTIOxzkLLAe5cmu-1

Should cover

1. Account - main (10a)
2. Account - User profile (10b)
3. Account - Payment accounts (10c, 10d)

along with their presenter interface definition and its presenter (mocked) implementation (ideally the domain model should be defined and linked with a repository - data on the respository can be mocked of course)

**Comment by rodvar** [comment]
I'm helping @nostrbuddha with 10c as agreed

**Comment by HenrikJannsen** [comment]
Is that required for the MVP?

**Comment by rodvar** [comment]
@HenrikJannsen I do believe for the MVP to work we need to provide the user some sort of Account Payments setup (which is 10c in the design) ? Happy to be proved wrong to slash some stuff from the scope if we can

**Comment by rodvar** [comment]
we are getting block so raising the low-prio bar to start picking this up that will be needed for trading, I'm splitting up work with buddha here

**Comment by rodvar** [comment]
I'm gonna contribute with 10a and 10b screens and functionality

**Comment by rodvar** [comment]
10a/b done

**Comment by rodvar** [comment]
done with the above
