### ISSUE TITLE
Implement AndroidCatHashService

### ISSUE THREAD

**Issue by HenrikJannsen** [bisq-network/bisq-mobile#58]
We need to get an Android implementation for creating the catHash images (profile images).

Kotlin class: `network.bisq.mobile.android.node.service.AndroidCatHashService`

Here are the java fx classes:
`bisq.desktop.components.cathash.JavaFxCatHashService` using `bisq.desktop.common.utils.ImageUtil` for image composition

**Comment by rodvar** [comment]
duplicated of https://github.com/bisq-network/bisq-mobile/issues/44

**Comment by rodvar** [comment]
thanks for the details @HenrikJannsen I'll take a look this week!

**Comment by rodvar** [comment]
this is done now with the recent merge
