### ISSUE TITLE
Android UI not taking full screen (top bar color)

### ISSUE THREAD

**Issue by rodvar** [bisq-network/bisq-mobile#61]
- android top controls (time, wifi, etc) its not updating to the apps theme making it look as if the app is not using all the screen

**Comment by rodvar** [comment]
@nostrbuddha would you like to have a look at this?

**Comment by nostrbuddha** [comment]
Yes. I ll do this

**Comment by rodvar** [comment]
fixed with https://github.com/bisq-network/bisq-mobile/pull/69
