### ISSUE TITLE
Add market icons from Bisq 2

### ISSUE THREAD

**Issue by HenrikJannsen** [bisq-network/bisq-mobile#65]
Currently there are icons for USD, EUR and GBP.
We should add all market icons from Bisq 2.
Path:
`bisq2/apps/desktop/desktop/src/main/resources/images/markets/fiat-logos/`

**Comment by rodvar** [comment]
probably buddha is the man for the job? :) @nostrbuddha ?

**Comment by nostrbuddha** [comment]
Yes. Pls assign this to me. Will populate all currencies in Exchange screen

**Comment by rodvar** [comment]
@nostrbuddha can we close this one?

**Comment by rodvar** [comment]
I think this is done, @nostrbuddha advice otherwise, closing for now

**Comment by nostrbuddha** [comment]
Yes. Henrik added all icons.
