### ISSUE TITLE
Define concept for native mobile notifications

### ISSUE THREAD

**Issue by HenrikJannsen** [bisq-network/bisq-mobile#8]
The notifications concept for Bisq 2 is based on desktop notifications, which obviously is not appropriate to mobile.

We should define the concept how to use mobile notifications and consider privacy-protecting solutions.

**Comment by rodvar** [comment]
I'll put my comments from the Matrix discussion here and comment a bit more on the rationale

```
 We need to define first what notifications are we interested in and consider that we probably want the user to be able to turn them on/off (this is integrated with the OS these days). In my head I've got the idea that we want to include for the MVP any notifications related to ongoing trades only as a must (things like "fancycat" has taken your sell offer!" and a tap takes you to the details) and optionally direct chat messages?
 
 in terms of notification impl, I would just had the service responsible for showing the notifications observing a device storage we have for that purpose, and then any controller/service in the app that wants the user to be notified simply has to use the component that writes to that storage. That would be my approach.
```

To levarage the notifications system of each platform, we'll need to do some OS setup. KMP alraedy has some libs implemented that make it easier to do this, we'll have to R&D this when the time comes.

re `We should define the concept how to use mobile notifications and consider privacy-protecting solutions.` , what would be the privacy concerns? Notifications will be based on bisq activity and controlled within the app code.

**Comment by rodvar** [comment]
@HenrikJannsen moved this into a discussion (it was not enabled before, now it is )
