### ISSUE TITLE
Apps icons

### ISSUE THREAD

**Issue by rodvar** [bisq-network/bisq-mobile#93]
Add in the apps icons conforming to the different platform specs, and considering app type

 - androidNode -> it should be the normal bisq logo icon
 - xClients -> let's use the bisq logo with "inverted colors" (white lightgreen as opposed to black dark green)

**Comment by nis-ship-it** [comment]
Assign it to me

**Comment by rodvar** [comment]
@nostrbuddha buddha would you like to take on this one?

**Comment by rodvar** [comment]
done yesterday with merged pr
